site_name: RPGMTranslate Documentation
site_description: Documentation for RPGMTranslate
site_author: savannstm

repo_url: https://github.com/RPG-Maker-Translation-Tools/rpgmtranslate-qt
site_url: https://RPG-Maker-Translation-Tools.github.io/rpgmtranslate-qt
edit_uri: blob/main/docs/docs
repo_name: RPG-Maker-Translation-Tools/rpgmtranslate-qt

copyright: Licensed under WTFPL.

nav:
  - Home: index.md
  - Installation: installation.md
  - Text Editing: text-editing.md
  - Search Features: search.md
  - Batch Processing: batch-processing.md
  - Tasks: tasks.md
  - Settings: settings.md
  - Glossary: glossary.md
  - Rvpacker: rvpacker.md
  - Git: git.md
  - Asset Inspector: asset-inspector.md
  - Development: development.md

theme:
  name: material

  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top

  palette:
    scheme: slate
    primary: indigo
    accent: indigo

  logo: assets/rpgmtranslate-logo.png
  favicon: assets/rpgmtranslate-logo.png

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: ru
          name: Русский
          build: true
          nav_translations:
              Home: Главная
              Installation: Установка
              Search Features: Поиск
              Text Editing: Редактирование текста
              Batch Processing: Массовая обработка
              Tasks: Задачи
              Settings: Настройки
              Glossary: Глоссарий
              Rvpacker: Rvpacker
              Git: Git
              Asset Inspector: Обзорщик ассетов
              Development: Разработка
          site_name: "Документация для RPGMTranslate"
          site_description: "Документация для RPGMTranslate"

        - locale: zh-CN
          name: 简体中文
          build: true
          nav_translations:
              Home: 首页
              Installation: 安装
              Search Features: 搜索功能
              Text Editing: 文本编辑
              Batch Processing: 批量处理
              Tasks: 任务
              Settings: 设置
              Glossary: 术语表
              Rvpacker: Rvpacker
              Git: Git
              Asset Inspector: 资源检查器
              Development: 开发
          site_name: "RPGMTranslate 文档"
          site_description: "RPGMTranslate 文档"
